name: Run Tests on PR

# Trigger the workflow on pull requests targeting the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (replace '3.x' with your Python version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'  # Replace with your Python version (e.g., 3.9)

      # # Install dependencies (if you have a requirements.txt file)
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Install pytest
      - name: Install pytest
        run: pip install pytest

      # Run your pytest tests
      - name: Run tests
        run: pytest